export const CFG = {
  NODE_ENV: 'NODE_ENV',
  PORT: 'PORT',
  MONGO_URI: 'MONGO_URI',
  REDIS_URL: 'REDIS_URL',
  ALERT_WEBHOOK_URL: 'ALERT_WEBHOOK_URL',
  INGEST_TOKEN: 'INGEST_TOKEN',
  LOG_LEVEL: 'LOG_LEVEL',
} as const;
